apiVersion: v1
kind: Service
metadata:
  name: service-gravitee-management-api
  labels:
    name: service-gravitee-management-api
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8083
    targetPort: 8083
  selector:
    app: gravitee-management-api