apiVersion: v1
kind: Service
metadata:
  name: service-gravitee-gateway
  labels:
    name: service-gravitee-gateway
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
  selector:
    app: gravitee-gateway