apiVersion: v1
kind: Secret
metadata:
  name: mongosecret
type: Opaque
data:
  gravitee.management.mongodb.username: GRAVITEE_MONGO_USERNAME
  gravitee.management.mongodb.password: GRAVITEE_MONGO_PASSWORD
  gravitee.management.mongodb.dbname: GRAVITEE_MONGO_DBNAME
  gravitee.management.mongodb.host: MONGO_HOST
  gravitee.management.mongodb.port: MONGO_PORT
  ds.mongodb.host: MONGO_HOST
  ds.mongodb.port: MONGO_PORT
