apiVersion: v1
kind: Service
metadata:
  name: service-gravitee-ui
  labels:
    name: service-gravitee-ui
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: gravitee-ui